name: CI Test & Build

on:
    pull_request:
        branches: [master, develop]
    workflow_call:

jobs:
    build:
        name: "Test & Build"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use local frontend-test-build action
              uses: ./.github/actions/frontend-test-build
